<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright © 2018 - 2020 by Renaud Guillard (dev@nore.fr) -->
<!-- Distributed under the terms of the MIT License, see LICENSE -->

<!-- Embed Parser and ProgramInfo derivated modules -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:prg="http://xsd.nore.fr/program">

	<xsl:import href="parser.xsl" />
	<xsl:import href="programinfo.xsl" />

	<xsl:output method="text" encoding="utf-8" />

	<xsl:template match="/">
		<xsl:value-of select="$prg.python.codingHint" />
		<xsl:if test="$prg.python.generationMode = 'generateMerge'">
			<xsl:text>""" Generated by ns-xml """</xsl:text>
			<xsl:value-of select="$str.endl" />
		</xsl:if>
		
		<xsl:value-of select="$prg.python.copyright" />
		<xsl:value-of select="$str.endl" />

		<xsl:call-template name="prg.python.base.output" />
		<xsl:call-template name="prg.python.programinfo.output" />

		<xsl:if test="$prg.python.generationMode = 'generateMerge'">
			<xsl:value-of select="$str.endl" />
			<xsl:text>""" End of ns-xml code """</xsl:text>
			<xsl:value-of select="$str.endl" />
		</xsl:if>

	</xsl:template>
</xsl:stylesheet>
